In [2]:
import numpy as np

# 1. Створити одновимірний масив з перших 20 натуральних чисел
arr1 = np.arange(1, 21)
print("Одновимірний масив:", arr1)

Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
import numpy as np

# 2. Створити матрицю 4x4, заповнену одиницями
matrix1 = np.ones((4, 4))
print("Матриця 4x4 з одиницями:\n", matrix1)

Матриця 4x4 з одиницями:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
import numpy as np

# 3. Масив 5x5 з випадковими числами від -1 до 1
matrix2 = np.random.uniform(-1, 1, (5, 5))
print("Матриця 5x5 [-1,1]:\n", matrix2)

Матриця 5x5 [-1,1]:
 [[-0.70320333  0.21933108 -0.4193991   0.06447865  0.49530797]
 [ 0.11221058 -0.85375775 -0.67431881  0.39191035 -0.61567587]
 [ 0.51892379  0.80625171  0.94749168 -0.11701258  0.50331525]
 [-0.1477641  -0.09110264 -0.70069692  0.21833886 -0.41464809]
 [ 0.48326295  0.28591977  0.24095639  0.8954994  -0.12706844]]


In [5]:
import numpy as np

# 4. Масив 3x3 з випадковими числами від 0 до 1
matrix3 = np.random.rand(3, 3)
print("Матриця 3x3 [0,1]:\n", matrix3)

Матриця 3x3 [0,1]:
 [[0.87209547 0.69246453 0.68012439]
 [0.47487245 0.24380353 0.6905923 ]
 [0.7313517  0.98454594 0.9165329 ]]


In [6]:
import numpy as np

# 5. Два масиви по 6 елементів та поелементні операції
arr2 = np.random.randint(1, 21, 6)
arr3 = np.random.randint(1, 21, 6)

print("Масив 1:", arr2)
print("Масив 2:", arr3)

print("Додавання:", arr2 + arr3)
print("Віднімання:", arr2 - arr3)
print("Множення:", arr2 * arr3)

Масив 1: [20  3  4 17 14  7]
Масив 2: [14 10 20 18  4 20]
Додавання: [34 13 24 35 18 27]
Віднімання: [  6  -7 -16  -1  10 -13]
Множення: [280  30  80 306  56 140]


In [7]:
import numpy as np

# 6. Множення матриць 3x2 і 2x4
A = np.random.randint(1, 6, (3, 2))
B = np.random.randint(1, 6, (2, 4))

print("Матриця A:\n", A)
print("Матриця B:\n", B)

result = np.dot(A, B)
print("Результат множення:\n", result)

Матриця A:
 [[4 5]
 [2 2]
 [4 2]]
Матриця B:
 [[5 5 2 3]
 [5 4 2 5]]
Результат множення:
 [[45 40 18 37]
 [20 18  8 16]
 [30 28 12 22]]


In [8]:
import numpy as np

# 7. Транспонування матриці 3x3
matrix4 = np.random.rand(3, 3)
print("Початкова матриця:\n", matrix4)

transpose = matrix4.T
print("Транспонована матриця:\n", transpose)

Початкова матриця:
 [[0.13993178 0.69257229 0.34413603]
 [0.06914284 0.53058703 0.36990191]
 [0.62394001 0.9768053  0.91294141]]
Транспонована матриця:
 [[0.13993178 0.06914284 0.62394001]
 [0.69257229 0.53058703 0.9768053 ]
 [0.34413603 0.36990191 0.91294141]]


In [9]:
import numpy as np

# 8. Різниця двох матриць 3x3
matrix5 = np.random.randint(1, 11, (3, 3))
matrix6 = np.random.randint(1, 11, (3, 3))

print("Матриця 1:\n", matrix5)
print("Матриця 2:\n", matrix6)

diff = matrix5 - matrix6
print("Різниця:\n", diff)

Матриця 1:
 [[ 2  6  2]
 [10  3  8]
 [ 7  4 10]]
Матриця 2:
 [[ 7  3  7]
 [ 5  4 10]
 [ 8  9  2]]
Різниця:
 [[-5  3 -5]
 [ 5 -1 -2]
 [-1 -5  8]]


In [10]:
import numpy as np

# 9. Добуток двох матриць 3x3
matrix7 = np.random.randint(-5, 6, (3, 3))
matrix8 = np.random.randint(-5, 6, (3, 3))

print("Матриця 1:\n", matrix7)
print("Матриця 2:\n", matrix8)

product = np.dot(matrix7, matrix8)
print("Добуток:\n", product)

Матриця 1:
 [[ 1 -5  3]
 [ 0  2  0]
 [ 4 -2  1]]
Матриця 2:
 [[-2 -4 -2]
 [-2  0  0]
 [ 0  3  1]]
Добуток:
 [[  8   5   1]
 [ -4   0   0]
 [ -4 -13  -7]]


In [11]:
import numpy as np

# 10. Сума елементів кожного рядка (вектор-стовпчик)
matrix9 = np.random.uniform(-1, 1, (3, 3))
print("Матриця:\n", matrix9)

row_sums = np.sum(matrix9, axis=1).reshape(-1, 1)
print("Вектор-стовпчик сум:\n", row_sums)

Матриця:
 [[ 0.64922176 -0.46257079 -0.18461124]
 [ 0.52134893 -0.16782649  0.17734985]
 [ 0.8202476  -0.84215372  0.09395467]]
Вектор-стовпчик сум:
 [[0.00203974]
 [0.53087228]
 [0.07204854]]
